const NotificationType = {
  ORDER_PLACED: 'ORDER_PLACED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  ORDER_SHIPPED: 'ORDER_SHIPPED',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  USER_REGISTERED: 'USER_REGISTERED',
  PASSWORD_RESET: 'PASSWORD_RESET',
  ADMIN_ALERT: 'ADMIN_ALERT',
  SYSTEM_MAINTENANCE: 'SYSTEM_MAINTENANCE'
};

export default NotificationType;