spring.datasource.url=jdbc:postgresql://localhost:5432/sakshi_db
spring.datasource.username=sakshi
spring.datasource.password=sakshi123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect