spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/scrapify}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:secret}
jwt.secret=${JWT_SECRET:YTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI=}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=techsakshirautela@gmail.com
spring.mail.password=fvsf pwad nlxs bvxm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true